spring.application.name=taskmanager
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console (accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Show SQL queries in terminal & auto-create tables
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update