services:
  gvp-unit4:
    build: .
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: ${JWT_SECRET:YOUR_JWT_SECRET_HERE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID_HERE}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET_HERE}